version: "3.3"

services:
    rabbitmq_server:
        image: rabbitmq
        container_name: rabbitmq_server
        volumes:
          - ./rabbitmq:/var/lib/rabbitmq
        environment:
          - USER=$DOCKER_RABBITMQ_USER
          - PASSWORD=$DOCKER_RABBITMQ_PASSWORD
    
    redis_server:
        image: redis
        container_name: redis_server
        volumes:
          - ./redis:/var/lib/redis
        environment:
          - USER=$DOCKER_REDIS_USER
          - PASSWORD=$DOCKER_REDIS_PASSWORD
    
    celery:
        working_dir: /app
        build: .
        command: celery -A ecommerce worker -l INFO --logfile=celery_info.log
        depends_on:
          - rabbitmq_server
          - redis_server
        container_name: celery
        volumes:
          - ./celery:/var/lib/celery
    
    celery_beat:
        build: .
        command: celery -A ecommerce worker -B -l INFO -f celery_beat_info.log --logfile=celery_beat_info.log -n CELERY_BEAT --scheduler django_celery_beat.schedulers:DatabaseScheduler
        depends_on:
          - rabbitmq_server
          - redis_server
        container_name: celery_beat
        volumes:
          - ./celery_beat:/var/lib/celery_beat

    webserver: 
        build: .
        command: gunicorn ecommerce.wsgi -w 5 -b 0.0.0.0:8000
        depends_on:
          - rabbitmq_server
          - redis_server
        container_name: webserver
        ports:
          - "8000:8000"
        volumes:
          - .:/app
        extra_hosts:
          - "local_database:172.17.0.1"
