version: "3.3"

services:
    rabbitmq_server:
        image: bitnami/rabbitmq
        ports:
            - "5672:5672"
            - "25672:25672"
            - "15672:15672"
        container_name: rabbitmq_server
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
        environment:
            - USER=guest
            - PASSWORD=guest
    
    redis_server:
        image: redis
        ports:
            - "6379:6379"
        container_name: redis_server
        volumes:
            - ./redis:/var/lib/redis
        environment:
            - USER=guest
            - PASSWORD=guest
    
    celery: 
        build: .
        command: celery -A ecommerce worker -l info
        depends_on:
          - rabbitmq_server
          - redis_server
        container_name: celery
        volumes:
            - ./celery:/var/lib/celery
    
    celery_beat:
        build: .
        command: celery -A ecommerce beat -l info
        depends_on:
          - rabbitmq_server
          - redis_server
        container_name: celery_beat
        volumes:
            - ./celery_beat:/var/lib/celery_beat

    webserver: 
        build: .
        command: gunicorn ecommerce.wsgi -w 5 -b 0.0.0.0:8000
        depends_on:
            - rabbitmq_server
            - redis_server
        container_name: webserver
        ports:
            - "8000:8000"
        volumes:
            - .:/app
