# Generated by Django 3.2.7 on 2021-09-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='category'),
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory',
        ),
    ]
