# Generated by Django 3.2.7 on 2021-09-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210924_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Product title'),
        ),
    ]
