# Generated by Django 3.2.7 on 2021-09-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210924_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryfilter',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_filters', to='shop.subcategory', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategoryfilterchoice',
            name='subcategory_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='shop.subcategoryfilter', verbose_name='Product filter'),
        ),
    ]
