# Generated by Django 3.2.7 on 2021-09-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210928_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='order_steps',
            field=models.ManyToManyField(through='shop.OrderStep', to='shop.Step'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date when ordered'),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='date_step_begin',
            field=models.DateTimeField(null=True, verbose_name='Date step began'),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='date_step_end',
            field=models.DateTimeField(null=True, verbose_name='Date step ended'),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='shop.order', verbose_name='order'),
        ),
    ]
