# Generated by Django 3.2.7 on 2021-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210928_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image_href',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product image href'),
        ),
    ]
