# Generated by Django 3.2.6 on 2021-09-15 10:39

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City available for delivery', 'verbose_name_plural': 'Cities available for delivery'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Company employee', 'verbose_name_plural': 'Company employees'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='city',
            name='days_delivery',
            field=models.IntegerField(default=0, verbose_name='Delivery days'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='Астрахань', max_length=40, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.company_logo_directory, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('employee', 'employee')], max_length=10, verbose_name='User role'),
        ),
    ]
