# Generated by Django 3.2.7 on 2021-09-24 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Category name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.category_directory, verbose_name='Category image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Company name')),
                ('location', models.CharField(max_length=500, verbose_name='Company location')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Company phone number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shop.models.company_logo_directory, verbose_name='Company logo')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='Is it ordered by user')),
                ('shipped', models.BooleanField(default=False, verbose_name='Is order shipped')),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='Date when ordered')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': "User's cart",
                'verbose_name_plural': "User's Carts",
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_step_begin', models.DateField(null=True, verbose_name='Date step began')),
                ('date_step_end', models.DateField(null=True, verbose_name='Date step ended')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='order')),
            ],
            options={
                'verbose_name': "Order's Step",
                'verbose_name_plural': "Order's Steps",
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Subcategory name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.subcategory_directory, verbose_name='Subcategory image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='shop.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_filter', to='shop.subcategory', verbose_name='subcategory')),
            ],
            options={
                'verbose_name': 'Product filter',
                'verbose_name_plural': 'Product filters',
                'db_table': 'subcategory_filter',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryFilterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(default='', max_length=40, verbose_name='Choice')),
                ('subcategory_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='shop.subcategoryfilter', verbose_name='Product filter')),
            ],
            options={
                'verbose_name': 'Choice for product filter',
                'verbose_name_plural': 'Choices for product filter',
                'db_table': 'subcategory_filter_choice',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_step', models.CharField(default='Оплата', max_length=50, verbose_name='Step name')),
                ('orders', models.ManyToManyField(related_name='steps', through='shop.OrderStep', to='shop.Order')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.AddField(
            model_name='orderstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.step', verbose_name='step'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Product title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product description')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.company_product_directory, verbose_name='Product image')),
                ('slug', models.SlugField(blank=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company', verbose_name='company')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.subcategory', verbose_name='subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='phone number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=shop.models.company_logo_directory, verbose_name='photo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shop.company', verbose_name='company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company employee',
                'verbose_name_plural': 'Company employees',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity of item in order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Item in user order',
                'verbose_name_plural': 'Items in user order',
                'db_table': 'order_item',
                'ordering': ('item__title',),
                'unique_together': {('item', 'order')},
            },
        ),
    ]
