# Generated by Django 3.1.6 on 2021-04-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210408_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country_code',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city_area',
            new_name='street1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country_area',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zip',
            field=models.CharField(default=111111, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
