# Generated by Django 3.2.6 on 2021-09-15 13:07

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210903_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.category_directory),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.subcategory_directory),
        ),
    ]
