# Generated by Django 3.2.6 on 2021-09-15 14:51

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210915_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': "User's cart", 'verbose_name_plural': "User's Carts"},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item in user order', 'verbose_name_plural': 'Items in user order'},
        ),
        migrations.AlterModelOptions(
            name='orderstep',
            options={'verbose_name': "Order's Step", 'verbose_name_plural': "Order's Steps"},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.category_directory, verbose_name='Category image'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.company_product_directory, verbose_name='Product image'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.subcategory_directory, verbose_name='Subcategory image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Company location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.company_logo_directory, verbose_name='Company logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Company phone number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Is it ordered by user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date when ordered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='Is order shipped'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity of item in order'),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='date_step_begin',
            field=models.DateField(null=True, verbose_name='Date step began'),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='date_step_end',
            field=models.DateField(null=True, verbose_name='Date step ended'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name_step',
            field=models.CharField(default='Оплата', max_length=50, verbose_name='Step name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Subcategory name'),
        ),
    ]
