# Generated by Django 3.1.6 on 2021-04-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210417_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('CPU', 'CPU'), ('GPU', 'GPU'), ('MOTHERBOARD', 'Motherboard'), ('SNEAKERS', 'Sneakers'), ('POWER_SUPPLY', 'Power supply'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('RAM', 'Ram'), ('BODY', 'Body'), ('COOL', 'Coolers')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=20),
        ),
    ]
