# Generated by Django 3.2.6 on 2021-09-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210915_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('item__title',), 'verbose_name': 'Item in user order', 'verbose_name_plural': 'Items in user order'},
        ),
    ]
