# Generated by Django 3.1.6 on 2021-04-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
